### ISSUE TITLE
export code coverage (e.g. to codecov)

### ISSUE THREAD

**Issue by alexanderankin** [testcontainers/testcontainers-python#544]
get us a new fancy badge! splitting conversation from https://github.com/testcontainers/testcontainers-python/pull/460/files#r1536760017

**Comment by Tranquility2** [comment]
1. I Think we need some extra permissions on the repo to be able to use [coveralls](https://coveralls.io/) or [codecov](https://about.codecov.io/)
2. On a more positive note, I think I can get the workflow ready (mainly combine the reports from the different python versions).
I'll create a PR so you can see, hopefully its all that is needed except the actual integration with the external service.
After that it should be just a matter of adding
```
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
