### ISSUE TITLE
Bug: Testcontainers can't connect to set DOCKER_HOST in Gitlab CI

### ISSUE THREAD

**Issue by spreeni** [testcontainers/testcontainers-python#653]
**Describe the bug**

I can't get testcontainers to run in my Gitlab CI/CD pipeline, despite following the `docker:dind` setup, setting `DOCKER_HOST="tcp://docker:2375"` and `DOCKER_TLS_CERTDIR=""` (see https://java.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/ or https://samanta-reinosoa.medium.com/testing-fastapi-with-testcontainers-in-gitlab-b7c62068aeef).

testcontainers seems to be unable to connect to the specified docker host, I am getting the error
`docker.errors.DockerException: Error while fetching server API version: HTTPConnectionPool(host='docker', port=2375): Max retries exceeded with url: /version (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f102d2cd8d0>: Failed to resolve 'docker' ([Errno -2] Name or service not known)"))`

**To Reproduce**
Below my `.gitlab-ci.yml`:
```yaml
stages:
  - qa

default:
  image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "true"
  RYE_VERSION: "0.34.0"

cache:
  paths:
    - .venv/

.before_script: &before_script
    - curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
    - . "$HOME/.rye/env"
    - rye sync --no-lock
    - . .venv/bin/activate
    - python -V  # Print out python version for debugging

tests:
  stage: qa
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  before_script: *before_script
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%\|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
```

**Runtime environment**

Provide a summary of your runtime environment. Which operating system, python version, and docker version are you using? What is the version of `testcontainers-python` you are using? You can run the following commands to get the relevant information.

I am using `testcontainers-core==0.0.1rc1`.
