### ISSUE TITLE
Question: "Unknown MySQL server host 'mysql'" error for every test in GitHub Actions

### ISSUE THREAD

**Issue by alex-shef** [testcontainers/testcontainers-python#791]
## What are you trying to do?

conftest.py:
```
@pytest.fixture(scope="session")
def mysql_container():
    mysql = MySqlContainer("mysql:9").with_env("MYSQL_ROOT_PASSWORD", "root")
    with mysql:
        yield mysql


@pytest.fixture(scope="module", autouse=True)
def setup_database(mysql_container, django_db_blocker):
    settings.DATABASES["default"]["HOST"] = mysql_container.get_container_host_ip()
    settings.DATABASES["default"]["PORT"] = mysql_container.get_exposed_port(3306)
```

## Runtime environment

github_actions.yml
```
      - name: Pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: false
          job-summary: false
          custom-pytest: PYTHONPATH=. poetry run pytest
```

django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'mysql' (-3)")

Everything is working on the local machine. How to do this correctly in GitHub Actions?
